### PR TITLE
Attack manager

### PR DESCRIPTION
**Pull request by kamalist**
Currently it's the first version, without priorities, attacks are launched in random order with equal chances.

### CODE REVIEW

**Review by Alexflames — CHANGES_REQUESTED** [review]
The functionality in-game is still untested by me. The idea looks great and almost ready for deployment, the structure is quite good! Next I list some of changed that need to be done

Considering the Cuboid won't be the only enemy boss-type character, and the attackColor would probably not be used in all other bosses, it is recommended to separate attackColor from interface, probably by creating another base class just for Cuboid's attacks.

Also I would like to know the purpose of empty attack, probably by adding some comments /// before the class(component)

Debug messages (like in AttackManager.cs line 32, 35) should be removed if they aren't needed in the future

I also advice to erase some extra empty lines from EmptyAttack.cs

**Comment by Alexflames** [comment]
So I've tested your scene and it seems like you forgot to update it. Cuboid does not have attack manager, empty attack so I decided to recreate you scene myself and added pull request to your branch to include it

Things I found strange are:
- "Starting color" field in laser lines attack (black by default), what is the purpose of this?
- Time between attacks is zero even if in the editor it is shown as 5
- Empty attack duration by default should be lowered, for examples to 3 seconds

**Comment by kamalist** [comment]
"Starting color" field of laser lines is black by default because it was defined that way in the original  "LaserCubeLines.cs", check it. No special reason from my side, just porting existing code

**Comment by Alexflames** [comment]
Good changes! Merging the branch.
There can be further improvement, like making CuboidAttackManager inherit from AttackManager that has basic functionality. Attack manager can be used and other managers can be created from it

**Pull request merged**
