### PR TITLE
Boss movement and attacks improvement

### PR DESCRIPTION
**Pull request by Alexflames**
- Cuboid main script (for boss-like enemies) - CuboidMainLogic.cs
- Cuboid movement is separate from attacks
- Created BurstAttack as an analogue of ExtremeBaddyBurst
- Attack and Movement managers should be called in main script (target Update calls are faster than stock Update() calls)
- Movement can be applied inside attacks as shown in BurstAttack
- CuboidMain prefab that contains red laser-lines container
- FollowMove controller for cases when enemy follows your character
- Various fixes and improvements in ExtremeBaddyBurst, NPCMovement
- Changes that were merged from develop

### CODE REVIEW

**Comment by kamalist** [comment]
Good changes! I have no any serious objections. Some minor remarks and questions are listed below.

`IncreaseAverageBullet` method name might be a bit misleading (it increases the count, not the bullet itself).

Start() of `ExtremeBaddyProj.cs` is weird: why isn't the caller to add a created bullet to its internals instead of a bullet? I think that in this case a bullet shoudn't care about its creator if it has an independent being after creation.

I don't understand why `currentAttack` in `CuboidAttackManager` should be public but private (consider to introduce a getter for it or a method of checking `== null` instead of pulling the private field from the outside).

What's the benefits of packing `CuboidTheCube` in `CuboidMain` container?

**Comment by Alexflames** [comment]
> Good changes! I have no any serious objections. Some minor remarks and questions are listed below.

Thanks for reviewing me :)
> `IncreaseAverageBullet` method name might be a bit misleading (it increases the count, not the bullet itself).

Agree with this, will change

> Start() of `ExtremeBaddyProj.cs` is weird: why isn't the caller to add a created bullet to its internals instead of a bullet? I think that in this case a bullet shoudn't care about its creator if it has an independent being after creation.

I should comment it in the code, but the bullet spawning is done at server, and on spawn each client assigns it without any need for server to make it instead of clients. When a new client is connected, however, the bullets only appear and activate when the scene is loaded for **the** client. And he will sync variables of bullet with server and add it to the bullet updating list. Pretty complicated, if you have any questions, feel free to ask about it

> I don't understand why `currentAttack` in `CuboidAttackManager` should be public but private (consider to introduce a getter for it or a method of checking `== null` instead of pulling the private field from the outside).

I'll most likely change it, need a bit more time to get what the problem is

> What's the benefits of packing `CuboidTheCube` in `CuboidMain` container?

As stated in the pull request message, we can hold the references for Cuboid-specific laser lines in prefab, and instantiated CuboidMain will have laser lines with it, so it is more versatile and allows not to assign reference for this manually each time you create Cuboid in Scene

**Comment by kamalist** [comment]
>>I don't understand why currentAttack in CuboidAttackManager should be public but private (consider to introduce a getter for it or a method of checking == null instead of pulling the private field from the outside).
>I'll most likely change it, need a bit more time to get what the problem is

There are several problems with public fields. Firstly, making a field public you allow any outside object to change it and possibly interefere in component's work in unpleasent way. Finding these "outsider" may be a challenge. Secondly, you limit your possibilities for rewriting and changing internal implementation of the component. If outsiders rely on some public field, it is a great pain for you to remove this field if needed. A public field becomes a part of the public API, and changing of the public API is always painful. But if you hide your field with some method, lots of the problems disappear. You can even delete a corresponding field and logic, provide some compatibility implementation of getter for those who uses it: and noone breaks down (presumably :) ).

**Comment by Alexflames** [comment]
> > > I don't understand why currentAttack in CuboidAttackManager should be public but private (consider to introduce a getter for it or a method of checking == null instead of pulling the private field from the outside).
> > > I'll most likely change it, need a bit more time to get what the problem is
> 
> There are several problems with public fields. Firstly, making a field public you allow any outside object to change it and possibly interefere in component's work in unpleasent way. Finding these "outsider" may be a challenge. Secondly, you limit your possibilities for rewriting and changing internal implementation of the component. If outsiders rely on some public field, it is a great pain for you to remove this field if needed. A public field becomes a part of the public API, and changing of the public API is always painful. But if you hide your field with some method, lots of the problems disappear. You can even delete a corresponding field and logic, provide some compatibility implementation of getter for those who uses it: and noone breaks down (presumably :) ).

That makes a lot of sense. I'll keep that in mind for future PRs as well

**Pull request merged**
