### PR TITLE
Fixed the living sprites getting behind the laser grid and scene decorations

### PR DESCRIPTION
**Pull request by RayHammer**
I have no idea why the previous commits show up

### CODE REVIEW

**Review by Alexflames — CHANGES_REQUESTED** [review]
Hi, RayHammer! 
Your idea might work but in `FirstScene.unity` sorting layer in editor is shown as `unknown-layer`, not sure what exactly you did there. If you changed project settings when adding sorting layer, then you should corresponding file in your commit

**Comment by Alexflames** [comment]
(github bot ping)

**Comment by RayHammer** [comment]
It's weird that the TagManager.asset didn't show up as changed. I've fixed it now

**Comment by Alexflames** [comment]
It works

**Pull request merged**
